[pytest]

testpaths = src/main/api/tests src/main/ui/tests

python_files = test_*.py *_test.py

pythonpath = .

markers =
    debug: Debug
    api: mark test as API test
    test: Test
    ui: mark test as UI test
    regression: regressions test

addopts =
    --junitxml=reports/all_tests.xml
    --html=reports/all_tests.html
    --self-contained-html
    --alluredir=reports/allure
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure

