backend_url=http://localhost:4111/api/v1
ui_base_url=http://localhost:3001
admin_account=admin
admin_password=admin
admin_page=/admin
user_page=/dashboard
#server = http://localhost:4111/api
#api_version = /v1