class AlertMessage:
    USER_CREATED = "User created successfully!"
    USER_CREATED_FAILED = "Failed to create user"
    NAME_UPDATE = "Name updated successfully!"
    NAME_UPDATED_FAILED = "Please enter a valid name"
    ACCOUNT_CREATED = "Account Created!"
    DEPOSIT_ACCOUNT = "Successfully deposited"
    DEPOSIT_ACCOUNT_FAILED = "Please enter a valid amount"
    TRANSFER_VALID = "Successfully transferred"
    TRANSFER_FAILED = "Error: Invalid transfer: insufficient funds or invalid accounts"
    NOT_CHECK_CONFIRM = "Please fill all fields and confirm"
    DEPOSIT_MORE_MAX = "Please deposit less or equal to 5000$"
    TRANSFER_MORE_MAX = "Error: Transfer amount cannot exceed 10000"
    TRANSFER_BELOW_MIN = "Error: Transfer amount must be at least 0.01"

