from typing import Protocol, Optional, Union

import requests

from src.main.api.models.base_model import BaseModel

class CrudEndpointInterface(Protocol):
    def post(self, model: Optional[BaseModel] = None, **params) -> requests.Response: ...
    def get(self, model: Optional[BaseModel] = None, id: Optional[int] = None, **params) -> requests.Response: ...
    def update(self, model: Optional[BaseModel] = None, id: Optional[int] = None, **params) -> requests.Response: ...
    def delete(self, id: int, **params) -> Union[BaseModel, bool]: ...
